db.monitores.insertOne(
    {
    _id:1, 
    marca: "acer", 
    modelo: "XV272P", 
    pulgadas: [24, 27], 
    ratioAspecto: {formato: "16:9", curvatura: false},
    pantalla: 
            {
            resolucion: "FHD", 
            panel: "IPS", 
            resfresco: 144, 
            bitsProfundidad: 8, 
            brillo: 400,
            HDR: 400
            },
    peana:
            {
            ajustable: ["altura", "inclinacion", "rotacion"],
            materiales: ["plastico", "aluminio", "goma"],
            colores: ["negro", "rojo"]
            },
    espacioColor: [{estandar: "sRGB", cobertura: 99},],
    altavoces: true,
    tecnologias: 
            ["freesync", "gsync"], 
    conectividad: 
            {
            USB: 
                {
                version:3.0, 
                number: 4
                }, 
            HDMI: 
                {
                version: 2.0, 
                number: 2
                }, 
            DisplayPort: 
                {
                version: 1.4, 
                number: 1
                }
            }, 
    anunciado: new Date("2018-10-28"),
    puestoEnVenta: new Date ("2019-3-15"),
    comprar: [{tienda: "amazon", precio: 260.90}, {tienda: "pccomponentes", precio: 260}, {tienda: "paginaoficial", precio: 260}]
    }
)
db.monitores.deleteMany({})
db.monitores.insertMany([
    { _id: 1, marca: "acer", modelo: "XV272P", pulgadas: [24,27], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "FHD", panel: "IPS", refresco: 144, bitsProfundidad: 8, brillo: 400, HDR: 400}, peana: {ajustabilidad: ["altura", "inclinacion", "rotacion", "orientacion"], materiales: ["plastico", "aluminio", "goma"], colores: ["negro", "rojo"]}, espacioColor: [{estandar: "sRGB", cobertura: 99}], altavoces: true, tecnologias: ["freesync"], conectividad: { USB: {version: 3.0, number: 4}, HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.4, number: 1}}, anunciado: new Date("2018-10-28"), puestoEnVenta: new Date ("2019-3-15"), comprar: [{tienda: "amazon", precio: 280}, {tienda: "pccomponentes", precio: 265.75}, {tienda: "paginaoficial", precio: 260}]},
    { _id: 2, marca: "alienware", modelo: "AW3821DW", pulgadas: [38], ratioAspecto: {formato: "21:9", curvatura: true}, pantalla: {resolucion: "WQHD", panel: "NIPS", refresco: 144, bitsProfundidad: 10, brillo: 450, HDR: 600}, peana: {ajustabilidad: ["altura", "inclinacion", "orientacion"], materiales: ["plastico", "goma"], colores: ["blanco", "negro"]}, espacioColor: [{estandar: "sRGB", cobertura: 130}, {estandar: "DCIP3", cobertura: 95}], altavoces: false, tecnologias: ["gsync"], conectividad: { USB: {version:3.2, number: 5}, HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1, number: 1.4}}, anunciado: new Date("2020-11-3"), puestoEnVenta: new Date ("2021-2-12"), comprar: [{tienda: "amazon", precio: 1424.35}, {tienda: "pccomponentes", precio: 1746.19}, {tienda: "paginaoficial", precio:1299.99}]},
    { _id: 3, marca: "alienware", modelo: "AW2721D", pulgadas: [27], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "QHD", panel: "IPS", refresco: 240, bitsProfundidad: 10, brillo: 600, HDR: 600}, peana: {ajustabilidad: ["altura", "inclinacion", "orientacion"], materiales: ["plastico", "goma"], colores: ["blanco", "negro"]}, espacioColor: [{estandar: "sRGB", cobertura: 131.3}, {estandar: "DCIP3", cobertura: 98}], altavoces: false, tecnologias: ["gsync"], conectividad: { USB: {version:3.2, number: 5}, HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.4, number: 1}}, anunciado: new Date("2020-11-3"), puestoEnVenta: new Date ("2021-2-12"), comprar: [{tienda: "pccomponentes", precio: 957}, {tienda: "paginaoficial", precio: 762}, {tienda: "LDLC", precio: 783}]},
    { _id: 4, marca: "lg", modelo: "29WN600", pulgadas: [22, 29], ratioAspecto: {formato: "21:9", curvatura: false}, pantalla: {resolucion: "WFHD", panel: "AHIPS", refresco: 75, bitsProfundidad: 8, brillo: 250}, peana: {ajustabilidad: ["inclinación"], materiales: ["plastico", "aluminio"], colores: ["blanco", "negro", "plateado"]}, espacioColor: [{estandar: "sRGB", cobertura: 99},], altavoces: true, tecnologias: [], conectividad: {HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.4, number: 1}}, anunciado: new Date("2020-4-21"), puestoEnVenta: new Date ("2020-11-10"), comprar: [{tienda: "amazon", precio: 229}, {tienda: "pccomponentes", precio: 228}, {tienda: "elcorteingles", precio:249}]},
    { _id: 5, marca: "benq", modelo: "GC2870", pulgadas: [24, 27, 28], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "FHD", panel: "VA", refresco: 60, bitsProfundidad: 8, brillo: 300}, peana: {ajustabilidad: ["inclinacion"], materiales: ["plastico"], colores: ["negro"]}, espacioColor: [{estandar: "sRGB", cobertura: 100}, {estandar: "NTSC", cobertura: 85}], altavoces: false, tecnologias: [], conectividad: {HDMI: {version: 1.4, number: 2}}, anunciado: new Date("2015-10-4"), puestoEnVenta: new Date ("2015-12-4"), comprar: [{tienda: "paginaoficial", precio: 150}]},
    { _id: 6, marca: "benq", modelo: "EX2780Q", pulgadas: [27], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "QHD", panel: "IPS", refresco: 144, bitsProfundidad: 10, brillo: 350, HDR: 400}, peana: {ajustabilidad: ["inclinacion"], materiales: ["plastico", "goma"], colores: ["bronce", "negro"]}, espacioColor: [{estandar: "RGB", cobertura: 90}, {estandar: "DCIP3", cobertura: 95}], altavoces: true, tecnologias: ["freesync"], conectividad: { USB: {version: 3.1, number: 1}, HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.4, number: 1}}, anunciado: new Date("2018-5-16"), puestoEnVenta: new Date ("2019-8-30"), comprar: [{tienda: "amazon", precio: 297.99}, {tienda: "pccomponentes", precio: 297.99}, {tienda: "paginaoficial", precio:379}, {tienda: "mediamarkt", precio: 299}]},
    { _id: 7, marca: "rog", modelo: "PG259QNR", pulgadas: [23,24], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "FHD", panel: "FIPS", refresco: 360, bitsProfundidad: 10, brillo: 400}, peana: {ajustabilidad: ["altura", "rotacion", "inclinacion", "orientacion"], materiales: ["plastico", "aluminio", "goma"], colores: ["bronce", "negro"]}, espacioColor: [], altavoces: false, tecnologias: ["gsync"], conectividad: { USB: {version: 3, number: 2}, HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.4, number: 1}}, anunciado: new Date("2020-5-28"), puestoEnVenta: new Date ("2021-2-14"), comprar: [{tienda: "amazon", precio: 628}, {tienda: "pccomponentes", precio: 628.99}, {tienda: "game", precio: 669}]},
    { _id: 8, marca: "samsung", modelo: "C49G95T", pulgadas: [38, 49], ratioAspecto: {formato: "32:9", curvatura: true}, pantalla: {resolucion: "DQHD", panel: "QVA", refresco: 240, bitsProfundidad: 10, brillo: 1000, HDR: 1000}, peana: {ajustabilidad: ["altura", "inclinacion", "orientacion"], materiales: ["plastico", "goma"], colores: ["blanco", "negro"]}, espacioColor: [{estandar: "sRGB", cobertura: 125}, {estandar: "RGB", cobertura: "92"}, {estandar: "NTSC", cobertura: "88"}, {estandar: "DCIP3", cobertura: 95}], altavoces: false, tecnologias: ["gsync"], conectividad: { USB: {version: 3.0, number: 2}, HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.4, number: 2}}, anunciado: new Date("2020-10-7"), puestoEnVenta: new Date ("2020-12-15"), comprar: [{tienda: "amazon", precio: 1979.10}, {tienda: "paginaoficial", precio:1499}, {tienda: "mediamarkt", precio: 1499}]},
    { _id: 9, marca: "asus", modelo: "PA279CV", pulgadas: [24, 27, 31], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "UHD", panel: "IPS", refresco: 60, bitsProfundidad: 10, brillo: 350}, peana: {ajustabilidad: ["altura", "inclinacion", "rotacion", "orientacion"], materiales: ["plastico", "aluminio"], colores: ["negro", "plateado"]}, espacioColor: [{estandar: "sRGB", cobertura: 100},], altavoces: true, tecnologias: [], conectividad: { USB: {version:3.0, number: 4}, HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.2, number: 1}}, anunciado: new Date("2019-4-14"), puestoEnVenta: new Date ("2019-11-15"), comprar: [{tienda: "amazon", precio: 649}, {tienda: "pccomponentes", precio: 529}, {tienda: "mediamarkt", precio: 429}]},
    { _id: 10, marca: "apple", modelo: "PROXDR", pulgadas: [32], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "UHD", panel: "IPS", refresco: 60, bitsProfundidad: 10, brillo: 1600, HDR: 1000}, altavoces: false, tecnologias: [], conectividad: { USB: {version: 3.0, number: 3}}, anunciado: new Date("2018-6-10"), puestoEnVenta: new Date ("2019-8-25"), comprar: [{tienda: "amazon", precio: 4976}, {tienda: "paginaoficial", precio: 5499}]},
    { _id: 11, marca: "msi", modelo: "G273QF", pulgadas: [27], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "WQHD", panel: "FIPS", refresco: 165, bitsProfundidad: 8, brillo: 300}, peana: {ajustabilidad: ["inclinacion"], materiales: ["plastico"], colores: ["negro"]}, espacioColor: [{estandar: "sRGB", cobertura: 125}, {estandar: "DCIP3", cobertura: 93}], altavoces: true, tecnologias: ["freesync", "gsync"], conectividad: {HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.2, number: 1}}, anunciado: new Date("2017-8-29"), puestoEnVenta: new Date ("2018-3-10"), comprar: [{tienda: "amazon", precio: 376.27}, {tienda: "pccomponentes", precio: 376.27}]},
    { _id: 12, marca: "dell", modelo: "S2721QS", pulgadas: [24, 27], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "UHD", panel: "IPS", refresco: 60, bitsProfundidad: 10, brillo: 350}, peana: {ajustabilidad: ["altura", "rotacion", "inclinacion", "orientacion"], materiales: ["aluminio", "plastico"], colores: ["plateado"]}, espacioColor: [{estandar: "sRGB", cobertura: 99},], altavoces: true, tecnologias: [], conectividad: {HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.2, number: 1}}, anunciado: new Date("2016-9-10"), puestoEnVenta: new Date ("2017-6-19"), comprar: [{tienda: "amazon", precio: 362.81}, {tienda: "paginaoficial", precio: 377}]},
    { _id: 13, marca: "lg", modelo: "27GP700", pulgadas: [27], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "FHD", panel: "IPS", refresco: 240, bitsProfundidad: 8, brillo: 400, HDR: 400}, peana: {ajustabilidad: ["inclinacion"], materiales: ["plastico"], colores: ["negro", "rojo"]}, espacioColor: [{estandar: "sRGB", cobertura: 99},], altavoces: false, tecnologias: ["freesync", "gsync"], conectividad: {HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.4, number: 1}}, anunciado: new Date("2018-7-10"), puestoEnVenta: new Date ("2018-10-30"), comprar: [{tienda: "paginaoficial", precio: 299.99}]},
    { _id: 14, marca: "hp", modelo: "OMEN27C", pulgadas: [27, 35], ratioAspecto: {formato: "16:9", curvatura: true}, pantalla: {resolucion: "QHD", panel: "VA", refresco: 240, bitsProfundidad: 8, brillo: 400, HDR: 450}, peana: {ajustabilidad: ["altura", "inclinacion"], materiales: ["plastico", "goma"], colores: ["negro"]}, espacioColor: [{estandar: "DCIP3", cobertura: 99},], altavoces: false, tecnologias: ["freesync"], conectividad: { USB: {version: 3.2, number: 2}, HDMI: {version: 2, number: 1}, DisplayPort: {version: 1.4, number: 1}}, anunciado: new Date("2021-7-7"), puestoEnVenta: new Date ("2021-10-23"), comprar: [{tienda: "paginaoficial", precio: 529.99}]},
    { _id: 15, marca: "aorus", modelo: "FI32QX", pulgadas: [31.9], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "QHD", panel: "IPS", refresco: 270, bitsProfundidad: 8, brillo: 600, HDR: 600}, peana: {ajustabilidad: ["altura", "rotacion", "inclinacion", "orientacion"], materiales: ["plastico", "aluminio"], colores: ["negro"]}, espacioColor: [{estandar: "sRGB", cobertura: 157}, {estandar: "RGB", cobertura: 95}, {estandar: "DCIP3", cobertura: 99}], altavoces: true, tecnologias: ["freesync", "gsync"], conectividad: { USB: {version: 3.0, number: 2}, HDMI: {version: 2.1, number: 2}, DisplayPort: {version: 1.4, number: 1}}, anunciado: new Date("2020-8-15"), puestoEnVenta: new Date ("2021-5-16"), comprar: [{tienda: "pccomponentes", precio: 744.26}]},
    { _id: 16, marca: "Philips", modelo: "276E8VJS", pulgadas: [27], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "UHD", panel: "IPS", refresco: 60, bitsProfundidad: 10, brillo: 350}, peana: {ajustabilidad: ["inclinacion"], materiales: ["aluminio", "plastico"], colores: ["negro", "plateado"]}, espacioColor: [{estandar: "sRGB", cobertura: 109}, {estandar: "NTSC", cobertura: 91}], altavoces: false, tecnologias: [], conectividad: {HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.2, number: 1}}, anunciado: new Date("2018-4-14"), puestoEnVenta: new Date ("2018-10-21"), comprar: [{tienda: "amazon", precio: 309.99}, {tienda: "pccomponentes", precio: 413.29}]},
    { _id: 17, marca: "acer", modelo: "CB382CUR", pulgadas: [37], ratioAspecto: {formato: "21:9", curvatura: true}, pantalla: {resolucion: "UHD", panel: "IPS", refresco: 75, bitsProfundidad: 10, brillo: 300}, peana: {ajustabilidad: ["altura", "orientacion", "inclinacion"], materiales: ["aluminio", "plastico"], colores: ["plateado", "negro"]}, espacioColor: [{estandar: "sRGB", cobertura: 100}, {estandar: "DCIP3", cobertura: 95}], altavoces: true, tecnologias: ["freesync"], conectividad: { USB: {version:3.1, number: 4}, HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.2, number: 1}}, anunciado: new Date("2021-5-20"), puestoEnVenta: new Date ("2021-8-19"), comprar: [{tienda: "amazon", precio: 1399}, {tienda: "visunext", precio: 1399}]},
    { _id: 18, marca: "huawei", modelo: "MATEVIEWGT", pulgadas: [27, 30, 34], ratioAspecto: {formato: "21:9", curvatura: true}, pantalla: {resolucion: "WQHD", panel: "VA", refresco: 165, bitsProfundidad: 10, brillo: 350}, peana: {ajustabilidad: ["altura", "inclinacion"], materiales: ["plastico", "aluminio"], colores: ["negro"]}, espacioColor: [{estandar: "sRGB", cobertura: 100}, {estandar: "DCIP3", cobertura: 90}], altavoces: true, tecnologias: [], conectividad: { USB: {version: 3.0, number: 2}, HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.4, number: 1}}, anunciado: new Date("2020-11-26"), puestoEnVenta: new Date ("2021-5-10"), comprar: [{tienda: "amazon", precio: 449}, {tienda: "paginaoficial", precio:499}]},
    { _id: 19, marca: "viewsonic", modelo: "VP2776", pulgadas: [24,27], ratioAspecto: {formato: "16:9", curvatura: false}, pantalla: {resolucion: "QHD", panel: "NIPS", refresco: 165, bitsProfundidad: 10, brillo: 300}, peana: {ajustabilidad: ["altura", "inclinacion", "rotacion", "orientacion"], materiales: ["aluminio", "plastico"], colores: ["negro"]}, espacioColor: [{estandar: "DCIP3", cobertura: 100},], altavoces: false, tecnologias: ["freesync"], conectividad: { USB: {version: 3.0, number: 5}, HDMI: {version: 2.0, number: 2}, DisplayPort: {version: 1.4, number: 1}}, anunciado: new Date("2020-9-30"), puestoEnVenta: new Date ("2021-1-16"), comprar: [{tienda: "amazon", precio: 380}, {tienda: "pccomponentes", precio: 390}, {tienda: "paginaoficial", precio: 399}]},
    { _id: 20, marca: "viewsonic", modelo: "VP3881A", pulgadas: [37], ratioAspecto: {formato: "21:9", curvatura: true}, pantalla: {resolucion: "UHD", panel: "AHIPS", resfresco: 60, bitsProfundidad: 10, brillo: 300}, peana: {ajustabilidad: ["altura", "inclinacion", "orientacion"], materiales: ["aluminio", "plastico"], colores: ["negro"]}, espacioColor: [{estandar: "sRGB", cobertura: 100}, {estandar: "RGB", cobertura: 86}, {estandar: "DCIP3", cobertura: 95}], altavoces: true, tecnologias: ["freesync"], conectividad: { USB: {version: 3.1, number: 4}, HDMI: {version: 2, number: 2}, DisplayPort: {version: 1.2, number: 1}}, anunciado: new Date("2019-4-26"), puestoEnVenta: new Date ("2020-6-8"), comprar: [{tienda: "amazon", precio: 1300}]},
])